begin;

create table if not exists public.worker_push_subscriptions (
  id bigint generated by default as identity primary key,
  worker_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists worker_push_subscriptions_worker_active_idx
  on public.worker_push_subscriptions(worker_id,active);

alter table public.worker_push_subscriptions enable row level security;

create or replace function public.worker_save_push_subscription(
  p_endpoint text,p_p256dh text,p_auth text,p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if auth.uid() is null or not exists(
    select 1 from public.profiles where id=auth.uid() and role='worker' and active
  ) then raise exception 'WORKER_ONLY'; end if;
  if length(coalesce(p_endpoint,''))<20 or length(coalesce(p_p256dh,''))<20 or length(coalesce(p_auth,''))<5 then
    raise exception 'INVALID_PUSH_SUBSCRIPTION';
  end if;
  insert into public.worker_push_subscriptions(worker_id,endpoint,p256dh,auth,user_agent,active,updated_at)
  values(auth.uid(),p_endpoint,p_p256dh,p_auth,p_user_agent,true,now())
  on conflict(endpoint) do update set
    worker_id=auth.uid(),p256dh=excluded.p256dh,auth=excluded.auth,
    user_agent=excluded.user_agent,active=true,updated_at=now();
end;
$function$;

create or replace function public.worker_disable_push_subscription(p_endpoint text)
returns void
language sql
security definer
set search_path to 'public'
as $function$
  update public.worker_push_subscriptions set active=false,updated_at=now()
  where worker_id=auth.uid() and endpoint=p_endpoint;
$function$;

grant execute on function public.worker_save_push_subscription(text,text,text,text) to authenticated;
grant execute on function public.worker_disable_push_subscription(text) to authenticated;

commit;
