create table if not exists public.payroll_entries (
  id bigint generated by default as identity primary key,
  worker_id uuid not null references public.profiles(id) on delete cascade,
  work_date date not null check (work_date >= date '2026-09-01'),
  attraction_id bigint references public.attractions(id),
  started_time time not null,
  ended_time time not null,
  duration_minutes integer not null check (duration_minutes > 0 and duration_minutes <= 960),
  day_type text not null check (day_type in ('NORMAL','HOLIDAY')),
  hourly_rate numeric(10,2) not null check (hourly_rate >= 0),
  base_amount numeric(12,2) not null check (base_amount >= 0),
  bonus numeric(12,2) not null default 0 check (bonus >= 0),
  deduction numeric(12,2) not null default 0 check (deduction >= 0),
  total_amount numeric(12,2) not null,
  note text,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','CANCELLED')),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  cancelled_by uuid references public.profiles(id),
  cancelled_at timestamptz
);

create index if not exists payroll_entries_worker_date_idx
  on public.payroll_entries(worker_id,work_date desc);
create index if not exists payroll_entries_date_idx
  on public.payroll_entries(work_date,status);

alter table public.payroll_entries enable row level security;
drop policy if exists payroll_entries_no_direct_access on public.payroll_entries;
create policy payroll_entries_no_direct_access on public.payroll_entries
  for all to authenticated using(false) with check(false);

create or replace function public.manager_add_payroll_entry(
  p_worker_id uuid,
  p_work_date date,
  p_attraction_id bigint,
  p_started_time time,
  p_ended_time time,
  p_day_type text,
  p_bonus numeric default 0,
  p_deduction numeric default 0,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path=public
as $function$
declare
  v_interval interval;
  v_minutes integer;
  v_rate numeric(10,2);
  v_base numeric(12,2);
  v_total numeric(12,2);
  v_id bigint;
  v_attraction text;
begin
  if not public.park_is_manager() then raise exception 'MANAGER_REQUIRED'; end if;
  if p_work_date < date '2026-09-01' then raise exception 'PAYROLL_STARTS_2026_09_01'; end if;
  if p_day_type not in ('NORMAL','HOLIDAY') then raise exception 'INVALID_DAY_TYPE'; end if;
  if coalesce(p_bonus,0) < 0 or coalesce(p_deduction,0) < 0 then raise exception 'INVALID_ADJUSTMENT'; end if;
  if not exists(select 1 from public.profiles where id=p_worker_id and role='worker') then raise exception 'WORKER_NOT_FOUND'; end if;
  select name into v_attraction from public.attractions where id=p_attraction_id;
  if v_attraction is null then raise exception 'ATTRACTION_NOT_FOUND'; end if;

  v_interval := p_ended_time - p_started_time;
  if v_interval <= interval '0' then v_interval := v_interval + interval '1 day'; end if;
  v_minutes := round(extract(epoch from v_interval)/60)::integer;
  if v_minutes <= 0 or v_minutes > 960 then raise exception 'INVALID_WORK_DURATION'; end if;

  if position('колесо победы' in lower(v_attraction)) > 0 then
    v_rate := case when p_day_type='HOLIDAY' then 200 else 180 end;
  else
    v_rate := case when p_day_type='HOLIDAY' then 180 else 150 end;
  end if;
  v_base := round(v_minutes::numeric/60*v_rate,2);
  v_total := round(v_base+coalesce(p_bonus,0)-coalesce(p_deduction,0),2);

  insert into public.payroll_entries(
    worker_id,work_date,attraction_id,started_time,ended_time,duration_minutes,
    day_type,hourly_rate,base_amount,bonus,deduction,total_amount,note,created_by
  ) values(
    p_worker_id,p_work_date,p_attraction_id,p_started_time,p_ended_time,v_minutes,
    p_day_type,v_rate,v_base,coalesce(p_bonus,0),coalesce(p_deduction,0),v_total,nullif(trim(p_note),''),auth.uid()
  ) returning id into v_id;
  return v_id;
end;
$function$;

create or replace function public.manager_cancel_payroll_entry(p_entry_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $function$
begin
  if not public.park_is_manager() then raise exception 'MANAGER_REQUIRED'; end if;
  update public.payroll_entries set status='CANCELLED',cancelled_at=now(),cancelled_by=auth.uid()
  where id=p_entry_id and status='ACTIVE';
  if not found then raise exception 'PAYROLL_ENTRY_NOT_FOUND'; end if;
end;
$function$;

create or replace function public.manager_payroll_entries(p_from date,p_to date)
returns table(
  id bigint,worker_id uuid,worker_name text,work_date date,attraction_id bigint,attraction_name text,
  started_time time,ended_time time,duration_minutes integer,day_type text,hourly_rate numeric,
  base_amount numeric,bonus numeric,deduction numeric,total_amount numeric,note text,status text,created_at timestamptz
)
language sql security definer set search_path=public
as $function$
  select e.id,e.worker_id,p.display_name,e.work_date,e.attraction_id,a.name,e.started_time,e.ended_time,
    e.duration_minutes,e.day_type,e.hourly_rate,e.base_amount,e.bonus,e.deduction,e.total_amount,e.note,e.status,e.created_at
  from public.payroll_entries e
  join public.profiles p on p.id=e.worker_id
  left join public.attractions a on a.id=e.attraction_id
  where public.park_is_manager() and e.work_date between greatest(p_from,date '2026-09-01') and p_to
  order by e.work_date desc,e.started_time desc,p.display_name;
$function$;

create or replace function public.manager_payroll_summary(p_from date,p_to date)
returns table(
  worker_id uuid,worker_name text,work_days bigint,duration_minutes bigint,base_amount numeric,
  bonus numeric,manual_deduction numeric,penalty_deduction numeric,total_amount numeric
)
language sql security definer set search_path=public
as $function$
  with earnings as (
    select p.id worker_id,p.display_name worker_name,
      count(distinct e.work_date) filter(where e.status='ACTIVE') work_days,
      coalesce(sum(e.duration_minutes) filter(where e.status='ACTIVE'),0)::bigint duration_minutes,
      coalesce(sum(e.base_amount) filter(where e.status='ACTIVE'),0) base_amount,
      coalesce(sum(e.bonus) filter(where e.status='ACTIVE'),0) bonus,
      coalesce(sum(e.deduction) filter(where e.status='ACTIVE'),0) manual_deduction
    from public.profiles p
    left join public.payroll_entries e on e.worker_id=p.id and e.work_date between greatest(p_from,date '2026-09-01') and p_to
    where p.role='worker' and public.park_is_manager()
    group by p.id,p.display_name
  ), penalties as (
    select n.worker_id,coalesce(sum(n.amount),0) penalty_deduction
    from public.worker_notices n
    where n.notice_type='PENALTY' and n.deduct_from_salary and n.status='ACTIVE'
      and (n.created_at at time zone 'Europe/Samara')::date between greatest(p_from,date '2026-09-01') and p_to
    group by n.worker_id
  )
  select e.worker_id,e.worker_name,e.work_days,e.duration_minutes,e.base_amount,e.bonus,e.manual_deduction,
    coalesce(p.penalty_deduction,0),round(e.base_amount+e.bonus-e.manual_deduction-coalesce(p.penalty_deduction,0),2)
  from earnings e left join penalties p on p.worker_id=e.worker_id
  where e.duration_minutes>0 or e.bonus>0 or e.manual_deduction>0 or coalesce(p.penalty_deduction,0)>0
  order by e.worker_name;
$function$;

create or replace function public.worker_my_payroll(p_from date,p_to date)
returns table(
  id bigint,work_date date,attraction_name text,started_time time,ended_time time,duration_minutes integer,
  day_type text,hourly_rate numeric,base_amount numeric,bonus numeric,deduction numeric,total_amount numeric,note text
)
language sql security definer set search_path=public
as $function$
  select e.id,e.work_date,a.name,e.started_time,e.ended_time,e.duration_minutes,e.day_type,e.hourly_rate,
    e.base_amount,e.bonus,e.deduction,e.total_amount,e.note
  from public.payroll_entries e left join public.attractions a on a.id=e.attraction_id
  where e.worker_id=auth.uid() and e.status='ACTIVE'
    and e.work_date between greatest(p_from,date '2026-09-01') and p_to
    and p_to-p_from between 0 and 31
  order by e.work_date desc,e.started_time desc;
$function$;

create or replace function public.worker_my_payroll_penalties(p_from date,p_to date)
returns numeric
language sql security definer set search_path=public
as $function$
  select coalesce(sum(n.amount),0)
  from public.worker_notices n
  where n.worker_id=auth.uid() and n.notice_type='PENALTY' and n.deduct_from_salary and n.status='ACTIVE'
    and (n.created_at at time zone 'Europe/Samara')::date between greatest(p_from,date '2026-09-01') and p_to
    and p_to-p_from between 0 and 31;
$function$;

grant execute on function public.manager_add_payroll_entry(uuid,date,bigint,time,time,text,numeric,numeric,text) to authenticated;
grant execute on function public.manager_cancel_payroll_entry(bigint) to authenticated;
grant execute on function public.manager_payroll_entries(date,date) to authenticated;
grant execute on function public.manager_payroll_summary(date,date) to authenticated;
grant execute on function public.worker_my_payroll(date,date) to authenticated;
grant execute on function public.worker_my_payroll_penalties(date,date) to authenticated;
