create table if not exists public.worker_notices (
  id bigint generated by default as identity primary key,
  worker_id uuid not null references public.profiles(id) on delete cascade,
  notice_type text not null check (notice_type in ('SAFETY', 'PENALTY')),
  message text not null check (char_length(trim(message)) between 3 and 500),
  amount numeric(12,2) not null default 0 check (amount >= 0),
  deduct_from_salary boolean not null default false,
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'CANCELLED')),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id)
);

create index if not exists worker_notices_worker_created_idx
  on public.worker_notices(worker_id, created_at desc);

alter table public.worker_notices enable row level security;

drop policy if exists worker_notices_no_direct_access on public.worker_notices;
create policy worker_notices_no_direct_access on public.worker_notices
  for all to authenticated using (false) with check (false);

create or replace function public.manager_create_worker_notice(
  p_worker_id uuid,
  p_notice_type text,
  p_message text,
  p_amount numeric default 0,
  p_deduct_from_salary boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare v_id bigint;
begin
  if not public.park_is_manager() then raise exception 'MANAGER_REQUIRED'; end if;
  if p_notice_type not in ('SAFETY','PENALTY') then raise exception 'INVALID_NOTICE_TYPE'; end if;
  if char_length(trim(coalesce(p_message,''))) < 3 then raise exception 'MESSAGE_REQUIRED'; end if;
  if p_notice_type = 'SAFETY' then
    p_amount := 0;
    p_deduct_from_salary := false;
  end if;
  if coalesce(p_amount,0) < 0 then raise exception 'INVALID_AMOUNT'; end if;
  if not exists(select 1 from public.profiles where id=p_worker_id and role='worker' and active) then
    raise exception 'WORKER_NOT_FOUND';
  end if;
  insert into public.worker_notices(worker_id,notice_type,message,amount,deduct_from_salary,created_by)
  values(p_worker_id,p_notice_type,trim(p_message),coalesce(p_amount,0),coalesce(p_deduct_from_salary,false),auth.uid())
  returning id into v_id;
  return v_id;
end;
$function$;

create or replace function public.manager_worker_notices()
returns table(
  id bigint, worker_id uuid, worker_name text, notice_type text, message text,
  amount numeric, deduct_from_salary boolean, status text, created_at timestamptz,
  acknowledged_at timestamptz, created_by_name text
)
language sql
security definer
set search_path = public
as $function$
  select n.id,n.worker_id,w.display_name,n.notice_type,n.message,n.amount,
    n.deduct_from_salary,n.status,n.created_at,n.acknowledged_at,m.display_name
  from public.worker_notices n
  join public.profiles w on w.id=n.worker_id
  join public.profiles m on m.id=n.created_by
  where public.park_is_manager()
  order by n.created_at desc
  limit 1000;
$function$;

create or replace function public.manager_cancel_worker_notice(p_notice_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $function$
begin
  if not public.park_is_manager() then raise exception 'MANAGER_REQUIRED'; end if;
  update public.worker_notices
  set status='CANCELLED',cancelled_at=now(),cancelled_by=auth.uid()
  where id=p_notice_id and status='ACTIVE';
  if not found then raise exception 'NOTICE_NOT_FOUND'; end if;
end;
$function$;

create or replace function public.worker_my_notices()
returns table(
  id bigint, notice_type text, message text, amount numeric,
  deduct_from_salary boolean, created_at timestamptz, acknowledged_at timestamptz
)
language sql
security definer
set search_path = public
as $function$
  select n.id,n.notice_type,n.message,n.amount,n.deduct_from_salary,n.created_at,n.acknowledged_at
  from public.worker_notices n
  where n.worker_id=auth.uid() and n.status='ACTIVE'
  order by n.created_at desc
  limit 100;
$function$;

create or replace function public.worker_acknowledge_notice(p_notice_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $function$
begin
  update public.worker_notices set acknowledged_at=coalesce(acknowledged_at,now())
  where id=p_notice_id and worker_id=auth.uid() and status='ACTIVE';
  if not found then raise exception 'NOTICE_NOT_FOUND'; end if;
end;
$function$;

create or replace function public.block_remote_attraction_replacement()
returns trigger
language plpgsql
set search_path = public
as $function$
begin
  if exists(
    select 1 from public.attractions a
    where a.id=new.attraction_id and position('колесо победы' in lower(a.name)) > 0
  ) then
    raise exception 'REPLACEMENT_DISABLED';
  end if;
  return new;
end;
$function$;

drop trigger if exists block_remote_attraction_replacement_trigger on public.replacement_requests;
create trigger block_remote_attraction_replacement_trigger
before insert or update of attraction_id,status on public.replacement_requests
for each row when (new.status in ('PENDING','ACTIVE'))
execute function public.block_remote_attraction_replacement();

insert into public.attraction_replacement_settings(attraction_id,enabled)
select id,false from public.attractions where position('колесо победы' in lower(name)) > 0
on conflict (attraction_id) do update set enabled=false;

grant execute on function public.manager_create_worker_notice(uuid,text,text,numeric,boolean) to authenticated;
grant execute on function public.manager_worker_notices() to authenticated;
grant execute on function public.manager_cancel_worker_notice(bigint) to authenticated;
grant execute on function public.worker_my_notices() to authenticated;
grant execute on function public.worker_acknowledge_notice(bigint) to authenticated;
