begin;

alter table public.replacement_requests
  add column if not exists due_at timestamptz,
  add column if not exists extended_by uuid,
  add column if not exists extension_reason text;

create table if not exists public.replacement_extensions (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.replacement_requests(id) on delete cascade,
  extended_by uuid not null references public.profiles(id),
  minutes_added integer not null check (minutes_added between 1 and 240),
  reason text not null check (char_length(trim(reason)) >= 2),
  previous_due_at timestamptz,
  new_due_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.replacement_extensions enable row level security;

create or replace function public.worker_request_replacement(p_attraction_id bigint, p_daily_code text)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_day_id bigint;
  v_substitute uuid;
  v_id bigint;
begin
  select id into v_day_id
  from public.business_days
  where status='OPEN' and daily_code=p_daily_code
  order by id desc limit 1;

  if v_day_id is null then raise exception 'INVALID_DAY_CODE'; end if;
  if coalesce((select enabled from public.attraction_replacement_settings where attraction_id=p_attraction_id),true)=false then
    raise exception 'REPLACEMENT_DISABLED';
  end if;
  if not exists (
    select 1 from public.worker_assignments
    where day_id=v_day_id and attraction_id=p_attraction_id and worker_id=auth.uid() and active
  ) then raise exception 'NOT_ASSIGNED_TO_ATTRACTION'; end if;

  select worker_id into v_substitute
  from public.day_replacement_workers
  where day_id=v_day_id and active
  order by assigned_at desc limit 1;

  if v_substitute is null then
    select id into v_substitute from public.profiles
    where role='worker' and active and job_title='REPLACEMENT'
    limit 1;
  end if;

  if v_substitute is null then raise exception 'NO_REPLACEMENT_WORKER'; end if;
  if v_substitute=auth.uid() then raise exception 'INVALID_REPLACEMENT_REQUEST'; end if;
  if exists (
    select 1 from public.replacement_requests
    where day_id=v_day_id and requester_id=auth.uid() and status in ('PENDING','ACTIVE')
  ) then raise exception 'REQUEST_ALREADY_EXISTS'; end if;

  insert into public.replacement_requests(day_id,attraction_id,requester_id,replacement_worker_id)
  values(v_day_id,p_attraction_id,auth.uid(),v_substitute)
  returning id into v_id;
  return v_id;
end;
$function$;

create or replace function public.worker_accept_replacement(p_request_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_r public.replacement_requests%rowtype;
  v_assignment_id bigint;
begin
  select * into v_r from public.replacement_requests where id=p_request_id for update;
  if v_r.id is null or v_r.replacement_worker_id<>auth.uid() or v_r.status<>'PENDING' then
    raise exception 'REQUEST_NOT_AVAILABLE';
  end if;
  if exists (
    select 1 from public.replacement_requests
    where replacement_worker_id=auth.uid() and status='ACTIVE'
  ) then raise exception 'REPLACEMENT_WORKER_BUSY'; end if;
  if exists (
    select 1 from public.replacement_requests q
    where q.day_id=v_r.day_id and q.replacement_worker_id=auth.uid() and q.status='PENDING'
      and (q.requested_at,q.id)<(v_r.requested_at,v_r.id)
  ) then raise exception 'WAIT_FOR_EARLIER_REQUEST'; end if;
  if coalesce((select enabled from public.attraction_replacement_settings where attraction_id=v_r.attraction_id),true)=false then
    raise exception 'REPLACEMENT_DISABLED';
  end if;
  if exists(select 1 from public.worker_assignments where day_id=v_r.day_id and worker_id=auth.uid() and active) then
    raise exception 'REPLACEMENT_WORKER_BUSY';
  end if;

  insert into public.worker_assignments(day_id,worker_id,attraction_id,assigned_by,assigned_at,active)
  values(v_r.day_id,auth.uid(),v_r.attraction_id,v_r.requester_id,now(),true)
  returning id into v_assignment_id;

  update public.replacement_requests
  set status='ACTIVE',accepted_at=now(),due_at=now()+interval '15 minutes',assignment_id=v_assignment_id
  where id=v_r.id;
end;
$function$;

create or replace function public.manager_extend_replacement(p_request_id bigint,p_minutes integer,p_reason text)
returns timestamptz
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_old timestamptz;
  v_new timestamptz;
begin
  if not public.park_is_manager() then raise exception 'MANAGER_ONLY'; end if;
  if p_minutes<1 or p_minutes>240 then raise exception 'INVALID_EXTENSION'; end if;
  if char_length(trim(coalesce(p_reason,'')))<2 then raise exception 'REASON_REQUIRED'; end if;

  select due_at into v_old from public.replacement_requests
  where id=p_request_id and status='ACTIVE' for update;
  if not found then raise exception 'REQUEST_NOT_ACTIVE'; end if;

  v_new:=greatest(coalesce(v_old,now()),now())+make_interval(mins=>p_minutes);
  update public.replacement_requests
  set due_at=v_new,extended_by=auth.uid(),extension_reason=trim(p_reason)
  where id=p_request_id;

  insert into public.replacement_extensions(request_id,extended_by,minutes_added,reason,previous_due_at,new_due_at)
  values(p_request_id,auth.uid(),p_minutes,trim(p_reason),v_old,v_new);
  return v_new;
end;
$function$;

create or replace function public.manager_replacement_dashboard()
returns table(
  id bigint,day_id bigint,attraction_id bigint,attraction_name text,
  requester_id uuid,requester_name text,replacement_worker_id uuid,replacement_worker_name text,
  status text,queue_position integer,requested_at timestamptz,accepted_at timestamptz,due_at timestamptz,
  seconds_remaining integer,overdue boolean,ended_at timestamptz
)
language sql
stable security definer
set search_path to 'public'
as $function$
  select r.id,r.day_id,r.attraction_id,a.name,
    r.requester_id,requester.display_name,r.replacement_worker_id,substitute.display_name,
    r.status,
    case when r.status='PENDING' then 1+(
      select count(*)::integer from public.replacement_requests q
      where q.day_id=r.day_id and q.replacement_worker_id=r.replacement_worker_id and q.status='PENDING'
        and (q.requested_at,q.id)<(r.requested_at,r.id)
    ) end,
    r.requested_at,r.accepted_at,r.due_at,
    case when r.status='ACTIVE' and r.due_at is not null then extract(epoch from (r.due_at-now()))::integer end,
    (r.status='ACTIVE' and r.due_at is not null and r.due_at<now()),r.ended_at
  from public.replacement_requests r
  join public.attractions a on a.id=r.attraction_id
  join public.profiles requester on requester.id=r.requester_id
  join public.profiles substitute on substitute.id=r.replacement_worker_id
  where public.park_is_manager()
    and r.day_id=(select id from public.business_days where status='OPEN' order by id desc limit 1)
    and r.status in ('PENDING','ACTIVE')
  order by case when r.status='ACTIVE' then 0 else 1 end,r.requested_at,r.id;
$function$;

create or replace function public.worker_replacement_queue(p_daily_code text)
returns table(
  day_id bigint,is_daily_replacement boolean,request_id bigint,request_role text,request_status text,
  queue_position integer,attraction_id bigint,attraction_name text,other_worker_name text,
  requested_at timestamptz,accepted_at timestamptz,due_at timestamptz,seconds_remaining integer,overdue boolean
)
language plpgsql
stable security definer
set search_path to 'public'
as $function$
declare v_day_id bigint; v_is_replacement boolean;
begin
  select id into v_day_id from public.business_days
  where status='OPEN' and daily_code=p_daily_code order by id desc limit 1;
  if v_day_id is null then raise exception 'INVALID_DAY_CODE'; end if;

  select exists(
    select 1
    from public.day_replacement_workers drw
    where drw.day_id=v_day_id and drw.worker_id=auth.uid() and drw.active
  )
    or exists(select 1 from public.profiles where id=auth.uid() and role='worker' and active and job_title='REPLACEMENT')
  into v_is_replacement;

  return query
  select v_day_id,v_is_replacement,r.id,
    case when r.replacement_worker_id=auth.uid() then 'SUBSTITUTE' else 'REQUESTER' end,
    r.status,
    case when r.status='PENDING' then 1+(
      select count(*)::integer from public.replacement_requests q
      where q.day_id=r.day_id and q.replacement_worker_id=r.replacement_worker_id and q.status='PENDING'
        and (q.requested_at,q.id)<(r.requested_at,r.id)
    ) end,
    r.attraction_id,a.name,
    case when r.replacement_worker_id=auth.uid() then requester.display_name else substitute.display_name end,
    r.requested_at,r.accepted_at,r.due_at,
    case when r.status='ACTIVE' and r.due_at is not null then extract(epoch from (r.due_at-now()))::integer end,
    (r.status='ACTIVE' and r.due_at is not null and r.due_at<now())
  from public.replacement_requests r
  join public.attractions a on a.id=r.attraction_id
  join public.profiles requester on requester.id=r.requester_id
  join public.profiles substitute on substitute.id=r.replacement_worker_id
  where r.day_id=v_day_id
    and (r.requester_id=auth.uid() or r.replacement_worker_id=auth.uid())
    and r.status in ('PENDING','ACTIVE')
  order by case when r.status='ACTIVE' then 0 else 1 end,r.requested_at,r.id;

  if not found then
    return query select v_day_id,v_is_replacement,null::bigint,
      case when v_is_replacement then 'STANDBY' else 'AVAILABLE' end,null::text,null::integer,
      null::bigint,null::text,null::text,null::timestamptz,null::timestamptz,null::timestamptz,null::integer,false;
  end if;
end;
$function$;

grant execute on function public.worker_request_replacement(bigint,text) to authenticated;
grant execute on function public.worker_accept_replacement(bigint) to authenticated;
grant execute on function public.worker_replacement_queue(text) to authenticated;
grant execute on function public.manager_extend_replacement(bigint,integer,text) to authenticated;
grant execute on function public.manager_replacement_dashboard() to authenticated;

commit;
